export default {
  SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
  SET_IN_CATEGORIES: 'SET_IN_CATEGORIES',
  SET_OUT_CATEGORIES: 'SET_OUT_CATEGORIES',
  SET_PAYMENTS: 'SET_PAYMENTS',
  SET_LOG_INPUT: 'SET_LOG_INPUT',
};
